export const REMOVE_ITEM = 'data/REMOVE_ITEM'
export const ADD_ITEM = 'data/ADD_ITEM'
export const MOVE_ITEM = 'data/MOVE_ITEM'
export const UPDATE_ITEM = 'data/UPDATE_ITEM'
export const CHANGE_PAGE = 'data/CHANGE_PAGE'
export const ADD_DATA = 'data/ADD_DATA'
